### ISSUE TITLE
npmjs is not being updated for new releases anymore

### ISSUE THREAD

**Issue by cuzzasoft** [node-gfx/node-canvas-prebuilt#113]
Having a look at https://www.npmjs.com/package/canvas-prebuilt it unfortunately doesn't list any new releases since `2.0.0-alpha.14`. Got caught on this today as was trying to figure out if the package was still being actively maintained.

**Comment by LinusU** [comment]
This has been merged into the main canvas package, depend on that one instead ☺️

**Comment by cuzzasoft** [comment]
Derp, of course - thanks mate 😄
