### ISSUE TITLE
nodejs v14.0.0 (node-v83 ABI, glibc)

### ISSUE THREAD

**Issue by ebal** [node-gfx/node-canvas-prebuilt#118]
Hi,

is it possible to release **canvas-v2.6.1-node-v83-linux-glibc-x64.tar.gz**  according to this:

https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json
```
"modules": 83, "runtime": "node",     "variant": "v8_8.1",               "versions": "14.0.0" },
```

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.0.0

Thanks in advance,

**Comment by TheJJ** [comment]
This was released in the meantime.

But now I'd like to have `canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz`. :smile: 
The windows/mac versions were released already.

**Comment by zbjornson** [comment]
Both are now released!
