### ISSUE TITLE
Getting 404 on v2.6.1/canvas-v2.6.1-node-v79-linux-musl-x64.tar.gz

### ISSUE THREAD

**Issue by AshishKapoor** [node-gfx/node-canvas-prebuilt#119]
## Error from CI:

```node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v79-linux-musl-x64.tar.gz ```

What am I missing?

**Comment by zbjornson** [comment]
Hi, please see the *Installation fails with a 404 in the log* section of https://github.com/Automattic/node-canvas/issues/1511
