### ISSUE TITLE
Travis decided to hang on canvas-prebuilt

### ISSUE THREAD

**Issue by asturur** [node-gfx/node-canvas-prebuilt#12]
Hello @chearon.
Today Travis decided that canvas-prebuilt should hang indefinitely.

i switched back fabricjs to canvas or i cannot run tests.

May have to do with the recent node upgrades?

https://github.com/kangax/fabric.js/pull/3983

you can look here to see the commit history i tried to fix.

**Comment by chearon** [comment]
Hmmm where does it show that canvas-prebuilt is hanging? I tried installing/loading the same version and same node version as you on Ubuntu 15.04:

```
$ npm install canvas-prebuilt@1.6.5-prerelease.1

> canvas-prebuilt@1.6.5-prerelease.1 install /home/caleb/node_modules/canvas-prebuilt
> node-pre-gyp install

[canvas-prebuilt] Success: "/home/caleb/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node" is installed via remote
/home/caleb
└── canvas-prebuilt@1.6.5-prerelease.1

npm WARN enoent ENOENT: no such file or directory, open '/home/caleb/package.json'
npm WARN caleb No description
npm WARN caleb No repository field.
npm WARN caleb No README data
npm WARN caleb No license field.
$ node -e 'console.dir(require("canvas-prebuilt"))'
{ [Function: Canvas]
  version: '1.6.5',
  cairoVersion: '1.14.2',
  jpegVersion: '8',
  gifVersion: '4.1',
  freetypeVersion: '2.5.2',
  Context2d: { [Function: CanvasRenderingContext2D] parseFont: [Function] },
  PNGStream: [Function: PNGStream],
  PDFStream: [Function: PDFStream],
  JPEGStream: [Function: JPEGStream],
  Image: { [Function: Image] MODE_IMAGE: 1, MODE_MIME: 2 },
  ImageData: [Function: ImageData],
  Font: [Function: Font] }
$ node -v
v6.11.0
```

But if it's the Travis Ubuntu image, I think you need 1.6.0 - see my comment [here](https://github.com/chearon/node-canvas-prebuilt/issues/11#issuecomment-306193171)

**Comment by asturur** [comment]
in the previous commits, before i switch back to canvas-prebuilt 1.6.0 ( that fails some font tests ) and then i switch to canvas 1.6.5 tests are hanged and do not complete.

While last week were completling fawlessly.

**Comment by chearon** [comment]
Was there ever a point where 1.6.5 worked on Travis? I don't think it will, although it should at least print a linker error. Would help if I could see the error or if you could make it reproducible in another repo, I can try to do that too but it might be a few days.

**Comment by asturur** [comment]
https://travis-ci.org/kangax/fabric.js/jobs/238342470#L264

sure look this commit. canvas prebuilt 1.6.5 was going very good once i moved to trusty distribution.
This was 6 days ago.
I started using prebuilt succesfully since 
https://travis-ci.org/kangax/fabric.js/jobs/210911242#L140  march 14

**Comment by chearon** [comment]
Hey @asturur are you still using `canvas-prebuilt`? Since you reported this I've added a couple of alpha 2.x versions. Today I changed the build for those versions so that it works on older systems and even ones without glib, so you might have better luck with them.

**Comment by asturur** [comment]
i ll try it. i want to really use.it

**Comment by joelwross** [comment]
@chearon I had a similar issue with tests failing on Travis Linux systems. Updating to `2.0.0-alpha.2` successfully fixed the problem for me!

**Comment by chearon** [comment]
Can't reproduce / probably not an issue anymore?
