### ISSUE TITLE
How to set mirror address when installing this package

### ISSUE THREAD

**Issue by littlee** [node-gfx/node-canvas-prebuilt#120]
In my country, downloading file from github is slowwww, how do I use a mirror when installing this package ?

the mirror I would use:

https://npm.taobao.org/mirrors/canvas-prebuilt/

**Comment by chearon** [comment]
Use [`npm install canvas --canvas_binary_host_mirror=url`](https://github.com/mapbox/node-pre-gyp#download-binary-files-from-a-mirror) to pick a mirror. It doesn't look like your link has the latest versions though.

**Comment by littlee** [comment]
cool

**Comment by niksw7** [comment]
Can you suggest how to do it for yarn2
