### ISSUE TITLE
Prebuilt binaries not found for 2.6.1 and node 15.8.0

### ISSUE THREAD

**Issue by billreynolds007** [node-gfx/node-canvas-prebuilt#124]
node--version reports 15.8.0
I am trying to install on AWS Linux 2.
I run,
  npm install --save canvas
but I encounter errors. Is there a previous version of node that is better or alternative approach?

npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@15.8.0 | linux | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/home/ec2-user/qarbine.services/testMods/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@15.8.0 (node-v88 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz

**Comment by lowlighter** [comment]
Having the same problem 😕 

From [release](https://github.com/node-gfx/node-canvas-prebuilt/releases) page it seems that binaries for node-v88 are present for both mac and windows but not for linux.
If you have root access on your Linux instance, you can install [required build tools](https://github.com/Automattic/node-canvas/wiki/Installation:-Ubuntu-and-other-Debian-based-systems) so node-gyp will be able to build node-canvas from source

I don't know if this repo is still maintained considering low activty though 😕

**Comment by zbjornson** [comment]
Node 15 + Canvas 2.6.1 + Linux prebuilds are now available. Thanks @chearon for his work on it!

**Comment by billreynolds007** [comment]
Thanks @chearon for you work!
