### ISSUE TITLE
TypeError: Canvas.registerFont is not a function

### ISSUE THREAD

**Issue by camer0** [node-gfx/node-canvas-prebuilt#24]
I am using the latest canvas-prebuilt@2.0.0-alpha.5

I'm not quite sure why it's doing this, and I've tried uninstalling and reinstalling and using older versions, but it still returns the same error. Any thoughts?

Edit: If I remove the `Canvas.registerFont()`, it gives me another error:
`TypeError: Image is not a constructor`

Also, I `console.log(Canvas)` and it outputs:
`{ [Function: Canvas] _registerFont: [Function: _registerFont] }`

It doesn't have a Image constructor, but oddly enough the `_registerFont` works

**Comment by chearon** [comment]
Yeah sorry about that, see #21. It'll be fixed on the next release of `canvas`.
