### ISSUE TITLE
Crash on debugging

### ISSUE THREAD

**Issue by john-terraspace** [node-gfx/node-canvas-prebuilt#25]
As soon as a breakpoint is set in the node.js process the native canvas module crashes with the following error:

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...s\canvas-prebuilt\canvas\build\Release\canvas.node
File: c:\projects\node-canvas-prebuilt\no...\nan_obj..._wrap.h
Line: 33

Expression: object->InternalFieldCount() > 0

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------

Running latest via npm install and npm rebuild
node version 8.5.0
on Windows 10 Pro 64bit

**Comment by john-terraspace** [comment]
I found this:
https://github.com/nodejs/node/issues/15099

which seems identical, yet this still seems to be occurring. I've tried building canvas myself directly and the same occurs.

**Comment by chearon** [comment]
See automattic/node-canvas#855. The fix was merged but it hasn't been released yet.

**Comment by john-terraspace** [comment]
I see that bug was last commented on in Dec 2016 ??? / then a confirmation in July. It seems to related to 1.6.6, while the release is now 1.6.7
Is there a way to install a later/possibly alpha version like 2.0 ?

**Comment by john-terraspace** [comment]
https://github.com/zbjornson/node-canvas/tree/prototype-fix

Grabbed a copy of this branch, and rebuilt, seems to fix it.

**Comment by zbjornson** [comment]
@john-terraspace all of the releases listed on the [releases page](https://github.com/node-gfx/node-canvas-prebuilt/releases) are in npm -- `npm install canvas-prebuilt@v2.0.0-alpha.5` for example.

**Comment by john-terraspace** [comment]
Thanks for that, I'll remember that in future, the custom build worked perfectly, just need it for debugging purposes anyway and will switch to the normal release once done.

Thanks
