### ISSUE TITLE
Support for node 9.0?

### ISSUE THREAD

**Issue by molant** [node-gfx/node-canvas-prebuilt#26]
Is there any major blockers (other than time) to add support for node 9.0 now that's published?

**Comment by chearon** [comment]
I was hoping to respond to you with "It's been done!" but NPM doesn't seem to work on Windows with node 9, and on top of that Travis's macOS builds are taking an hour right now.

`2.0.0-alpha.5` has binaries for node 9 Linux and node 9 macOS as of right now, but I'm still working through Windows and all of the other versions.

**Comment by molant** [comment]
> NPM doesn't seem to work on Windows 

I think I read somewhere that you needed the very last version of npm when using node 9. Dont know if node 9 has the latest one bundled but if not it might be worth a try.

Thanks!

**Comment by chearon** [comment]
Done! Thanks for making these issues so fast @molant

**Comment by molant** [comment]
Thanks!
