### ISSUE TITLE
Catch up on latest canvas alphas

### ISSUE THREAD

**Issue by chearon** [node-gfx/node-canvas-prebuilt#29]
Need to add alpha 6-9, also [this](https://github.com/Automattic/node-canvas/issues/1075#issuecomment-359642785), which makes `registerFont` unusable

**Comment by swftvsn** [comment]
Would it be possible to get this going? I really need the latest alphas.

**Comment by swftvsn** [comment]
Also can I help with the release?

**Comment by chearon** [comment]
Yeah, I spent a lot of time yesterday trying to figure out [this](https://ci.appveyor.com/project/chearon/node-canvas-prebuilt-ggow0#L200) - the Windows builds just randomly stopped working and I haven't made any progress on it 😞 I'm working on it though.

**Comment by chearon** [comment]
All caught up!
