### ISSUE TITLE
Support for CentOS6.x and node 8?

### ISSUE THREAD

**Issue by anvth** [node-gfx/node-canvas-prebuilt#32]
Is there anyway or version of node-canvas-prebuilt that would work with glibc 2.12?

**Comment by chearon** [comment]
Probably not, that's 8 years old :/ I wouldn't be able to find a distro that's still supported that has a glibc that old, or that compile a glibc that old.

**Comment by anvth** [comment]
I did expect this response. :laughing: Was just trying my luck.
