### ISSUE TITLE
issue: Cannot install any canvas builds on newer nodejs versions

### ISSUE THREAD

**Issue by KingDGrizzle** [node-gfx/node-canvas-prebuilt#37]
Hello.

Right now, on Windows at least, I'm unable to install the latest prebuilt version due to a 404 error.

I'm running node.js 10 with npm 6. This issue also occurred with node 9, using `npm i node-gfx/node-canvas-prebuilt`.
 
Anything I can do past building node-canvas manually?

Thanks!

**Comment by chearon** [comment]
Duplicate of #36 (will fix this today)
