### ISSUE TITLE
issue: Cannot require canvas-prebuilt due to missing files

### ISSUE THREAD

**Issue by KingDGrizzle** [node-gfx/node-canvas-prebuilt#39]
Hello!

In my attempts at require-ing canvas-prebuilt I hit a roadblock, as it just throws an error. Looking through your package.json, you set main to `./canvas/index.js`, but said file doesn't exist!

~Seems like replacing it with `./canvas/build/Release/canvas.node` fixed that.~
Any long-term solutions?

**Comment by chearon** [comment]
What version are you on? Both `latest` (`1.6.5-prerelease.1`) and `next` ( `2.0.0-alpha.12`) don't appear to have that issue, but earlier versions might have it.

**Comment by KingDGrizzle** [comment]
Latest master install (`npm i node-gfx/node-canvas-prebuilt`)

**Comment by chearon** [comment]
Ah sorry for the confusion but that isn't going to work - `prepublish.sh` has to be run in order to use it. The published package is different than the git source tree when you clone it. Can you install one of the versions instead?

**Comment by KingDGrizzle** [comment]
Ah, alright. Yes, indeed it works now, but it kinda sucks having to be a few versions behind, and, to me at least, it would make more sense to have those files in the tar.gz available to download (since that has the built stuff)

**Comment by chearon** [comment]
I have all the latest versions up. Do you mean 1.6? I'd recommend switching to the 2.x series. It's difficult for me to keep supporting 1.6.x, and the builds in that series are more limited. But I can add the latest, 1.6.10. I will keep this issue open until I do that.

**Comment by KingDGrizzle** [comment]
Oh, nono, I didn't mean that. What I meant is having the files the prebuilt script generates outside the npm releases via another tar archive to allow git installs (like I attempted)

**Comment by chearon** [comment]
I don't know what you're attempting but you wouldn't gain anything from that, the repo is for running CI servers. NPM releases are simply copies of node-canvas with a slight modification to download binaries from here.
