### ISSUE TITLE
Can't install on Linux machine

### ISSUE THREAD

**Issue by remel19** [node-gfx/node-canvas-prebuilt#41]
I am able to install this on my windows machine but can't install it on my Linux machine, my glibc is 2.17. 

I am able to install all the packages except canvas-prebuilt.  I am getting the following error.

npm install canvas-prebuilt

> canvas-prebuilt@1.6.5-prerelease.1 install /export/local/gis/src/test/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND csc csc:80
node-pre-gyp ERR! stack     at ClientRequest.onError (/export/local/gis/src/test/node_modules/tunnel-agent/index.js:177:17)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:315:30)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
node-pre-gyp ERR! stack     at Socket.socketErrorListener (_http_client.js:387:9)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at Socket.emit (events.js:211:7)
node-pre-gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
node-pre-gyp ERR! System Linux 3.10.0-693.2.2.el7.x86_64
node-pre-gyp ERR! command "/opt/rh/rh-nodejs8/root/usr/bin/node" "/export/local/gis/src/test/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /export/local/gis/src/test/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
tunneling socket could not be established, cause=getaddrinfo ENOTFOUND csc csc:80
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.5-prerelease.1 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas-prebuilt@1.6.5-prerelease.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zbjornson** [comment]
That usually means you're behind a proxy. Try this solution: https://stackoverflow.com/a/33892578/1218408.

**Comment by remel19** [comment]
Let's assume the problem is with node-pre-gyp proxy, then it shouldn't work on either Linux or windows. But it works on windows and not on Linux and both machine is using the same proxy settings. I am not sure how to debug this.

**Comment by chearon** [comment]
Closing because

> Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND csc csc:80

Makes it clear it's not an issue with node-canvas-prebuilt. Sorry we couldn't help more :(
