### ISSUE TITLE
win32 build - librsvg

### ISSUE THREAD

**Issue by timknip** [node-gfx/node-canvas-prebuilt#42]
Would be nice to compile win32 build with `HAVE_RSVG`.

Seems trivial as there's the pacman package `mingw64/mingw-w64-x86_64-librsvg`

Got it going in my fork of `node-canvas` : https://github.com/timknip/node-canvas/blob/master/util/msys64_preinstall.sh

**Comment by Khorynthium** [comment]
+1 It would be cool to have It for x64 too.

**Comment by CT1994** [comment]
+1 this will make it easier for people who are using svg

**Comment by chearon** [comment]
Done! (As of `canvas@2.1.0`)
