### ISSUE TITLE
Tar file canvas-prebuilt-v1.6.0-node-v64-win32-x64.tar.gz not found

### ISSUE THREAD

**Issue by jarssonn** [node-gfx/node-canvas-prebuilt#45]
Hi,
I've got a problem with archive containing 1.6.0 version of canvas-prebuilt.
https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v64-win32-x64.tar.gz is returning 404 not found.
Best regards

**Comment by chearon** [comment]
Canvas 1.6.0 doesn't support node 10. Try the latest in the 1.6.x series or one of the 2.0 alphas.
