### ISSUE TITLE
node-pre-gyp intermittently fails on yarn install

### ISSUE THREAD

**Issue by tjmehta** [node-gfx/node-canvas-prebuilt#54]
Hello! Thanks for this great module.
I am seeing intermittent failures when yarn installing my application dependencies. 

Here are the logs:

error An unexpected error occurred: "/<APP_DIR>/node_modules/canvas-prebuilt: Command failed.
Exit code: 1
Command: sh
Arguments: -c node_modules/.bin/node-pre-gyp install
Directory: /<APP_DIR>/node_modules/canvas-prebuilt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@9.1.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for \"/<APP_DIR>/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node\" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v59-linux-x64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: tunneling socket could not be established, statusCode=502
node-pre-gyp ERR! stack     at ClientRequest.onConnect (/<APP_DIR>/node_modules/tunnel-agent/index.js:165:19)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:328:30)
node-pre-gyp ERR! stack     at emitThree (events.js:145:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:227:7)
node-pre-gyp ERR! stack     at Socket.socketOnData (_http_client.js:471:11)
node-pre-gyp ERR! stack     at emitOne (events.js:125:13)
node-pre-gyp ERR! stack     at Socket.emit (events.js:221:7)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:265:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:252:11)
node-pre-gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:209:10)
node-pre-gyp ERR! System Linux 4.11.3-74_fbk19_4137_g80c4e13d593b
node-pre-gyp ERR! command \"/<APP_DIR>/node-dist/bin/node\" \"/<APP_DIR>/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp\" \"install\"
node-pre-gyp ERR! cwd /<APP_DIR>/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v9.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
tunneling socket could not be established, statusCode=502".

It actually may be an issue with tunnel-agent? Let me know what you think and if I can provide any more debug info.

Thanks!

**Comment by tjmehta** [comment]
Actually, I just realized it seems GitHub is responding with 502 sometimes

**Comment by chearon** [comment]
Seems like it... the tarball link in the error does download for me.
