### ISSUE TITLE
Stable 2.x version

### ISSUE THREAD

**Issue by j0tunn** [node-gfx/node-canvas-prebuilt#60]
Hi.
There are stable 2.x version of `canvas`, but no stable version of `canvas-prebuilt`:
```bash
$ npm view canvas
canvas@2.0.1

$ npm view canvas-prebuilt
canvas-prebuilt@2.0.0-alpha.14
```

But there are stable 2.x tags in this repo. Are there any plans to publish stable 2.x version?

**Comment by j0tunn** [comment]
Or may be `1.6.x` version could be published with https://github.com/node-gfx/node-canvas-prebuilt/pull/13 ? This bug breaks `npm install` in case of there are some other packages depending on `node-pre-gyp`

**Comment by delucis** [comment]
@j0tunn See #58 

You can now install `canvas` (>2) and automatically get `canvas-prebuilt` where builds are available.

@chearon A note in the README indicating that as of 2.x this repo is no longer intended for direct installation might be a good idea?

**Comment by j0tunn** [comment]
@delucis Thanks!
