### ISSUE TITLE
Update to Node 11

### ISSUE THREAD

**Issue by kachar** [node-gfx/node-canvas-prebuilt#62]
Following the upgrade of Node to 11 it seems the NODE_MODULE_VERSION has been changed from 64 to 67 and the prebuilt package is not found in the tarball list anymore:

`canvas-prebuilt-v1.6.11-node-v67-linux-x64.tar.gz`

```
$ node-pre-gyp install
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@11.0.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for ".../node_modules/resemblejs/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-linux-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (.../node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (.../node_modules/request/request.js:1062:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:449:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "/usr/local/bin/node" ".../node_modules/node-pre-gyp/bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd .../node_modules/resemblejs/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v11.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-linux-x64.tar.gz
```

**Comment by molant** [comment]
@chearon anything I can do to help with this?

**Comment by chearon** [comment]
You can add it [here](https://github.com/node-gfx/node-canvas-prebuilt/blob/master/ci/install.sh#L1) if you want, I'll try to be fast but currently I'm using CI for the librsvg builds

**Comment by molant** [comment]
@chearon can you start a new build? [`node-sass` is already using it](https://github.com/appveyor/ci/issues/2707#issuecomment-437180923)

**Comment by chearon** [comment]
I tried yesterday. According to https://github.com/appveyor/ci/issues/2707#issuecomment-437183191 it's coming soon.

**Comment by chearon** [comment]
AppVeyor finally deployed Node 11. Just released

Node 11 / Windows x64 / 2.1.0
Node 11 / Windows x64 / 2.0.1
Node 11 / Windows x64 / 2.0.0

completing this issue 🎉

**Comment by FezVrasta** [comment]
Hey guys, what's the version where this change was released?

1.6.11 (latest npm stable) doesn't seem to support it yet, and the 2.x versions are still alpha and I can't find any changelog to make sure I upgrade correctly.

Thanks.

**Comment by kachar** [comment]
You can find the prebuilt

**Comment by FezVrasta** [comment]
Thanks, I'm using `vega` and I get the warning saying Node 11 is not supported, I guess they have to upgrade something then...

**Comment by kachar** [comment]
As I see `vega-canvas` is stuck at `"canvas-prebuilt": "^1.6.5-prerelease.1"`

**Comment by LinusU** [comment]
Seems like what `vega` does is now built right into the Canvas library. Importing e.g. `createCanvas` or `loadImage` will work both in Node.js and in the browser, thanks to this file:

https://github.com/Automattic/node-canvas/blob/master/browser.js
