### ISSUE TITLE
Publish latest version in npm

### ISSUE THREAD

**Issue by molant** [node-gfx/node-canvas-prebuilt#63]
The latest release on [GitHub is `v2.0.1`](https://github.com/node-gfx/node-canvas-prebuilt/releases/tag/v2.0.1) but the latest published version on npm is [`2.0.0-alpha.14`](https://www.npmjs.com/package/canvas-prebuilt).

Did I miss something? Anything I can do to help?

Thanks!

**Comment by delucis** [comment]
@molant See #58 & #60 

You can now install `canvas` (>2) and automatically get `canvas-prebuilt` where builds are available.

README update coming in #61

**Comment by chearon** [comment]
Readme has been updated, sorry for the confusion

**Comment by molant** [comment]
Awesome!
