### ISSUE TITLE
Url Not Found

### ISSUE THREAD

**Issue by ernestomr87** [node-gfx/node-canvas-prebuilt#71]
vas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/Ernesto/Work/Projects/Leo/Simplekyc-ui/simplekyc-ui/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v11.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
### **

> 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-darwin-x64.t

**
the file extension is missing

**Comment by ernestomr87** [comment]
Exist URL
https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v46-darwin-x64.tar.gz
Dont Exist URL
https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-darwin-x64.tar.gz

**Comment by Zzzen** [comment]
I downgraded node to 8.15 and it worked. you can try it.

**Comment by LinusU** [comment]
Newer versions of Node.js are supported by Canvas 2.x, I would recommend upgrading from Canvas 1.x to 2.x.
