### ISSUE TITLE
prepublish script version

### ISSUE THREAD

**Issue by Apidcloud** [node-gfx/node-canvas-prebuilt#75]
Good evening!

Which version is prepublish.js expecting exactly?
Shouldn't it also be 2.3.1?

When I try that, it yields ```Not found: 2.3.1@latest```

Thanks!

**Comment by chearon** [comment]
Hey there, were you able to get everything working? It should be able to run on a fork with any version specified as a git tag but without the `v`, so `2.3.1` in your example. Also make sure to see the [wiki](https://github.com/node-gfx/node-canvas-prebuilt/wiki/Releasing-Binaries) which I've attempted to keep up-to-date.

**Comment by Apidcloud** [comment]
Yup, I thought the script was running automatically, but I had to call it manually instead. I also didn't know there was a wiki 😅Good to know! It seems to be up to date.
