### ISSUE TITLE
Regarding the recent failing build

### ISSUE THREAD

**Issue by LinusU** [node-gfx/node-canvas-prebuilt#76]
@chearon 

> Package libffi was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libffi.pc'
> to the PKG_CONFIG_PATH environment variable
> Package 'libffi', required by 'gobject-2.0', not found

I got the same error on my computer, it seems like Homebrew might have changed something 🤔 

The following env variable fixes it:

```sh
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
```

**Comment by chearon** [comment]
I swear it's something new every release 😑 thanks I'm trying that now!

**Comment by chearon** [comment]
Worked, thanks!
