### ISSUE TITLE
Add changelog to release notes

### ISSUE THREAD

**Issue by ajfarkas** [node-gfx/node-canvas-prebuilt#79]
It would be really helpful to me as an end user to be able to see the changes between releases with a changelog in the release notes. I currently have to dig into your commits to figure out what has changed, and how I'll be affected, or whether a bug I'm looking into has been resolved.

**Comment by zbjornson** [comment]
This repo isn't for node-canvas itself, it's just for the prebuild scripts. There's a changelog for canvas in its repo: https://github.com/Automattic/node-canvas/blob/master/CHANGELOG.md
